FROM docker.io/getterup/fedora-rocm7.1:latest AS builder
# vim: filetype=dockerfile

ARG FLAVOR=rocm
ARG PARALLEL=8

ARG ROCM7VERSION=7.1
ARG CMAKEVERSION=3.31.2

RUN git clone https://github.com/rjmalagon/ollama-linux-amd-apu.git /tmp/ollama-src
WORKDIR /tmp/ollama-src

ARG CMAKEVERSION
RUN curl -fsSL https://github.com/Kitware/CMake/releases/download/v${CMAKEVERSION}/cmake-${CMAKEVERSION}-linux-$(uname -m).tar.gz | tar xz -C /usr/local --strip-components 1
ENV LDFLAGS=-s


ENV PATH=/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/opt/rocm/bin:/opt/rocm/hcc/bin:$PATH
ARG PARALLEL
RUN --mount=type=cache,target=/root/.ccache \
    cmake --preset 'ROCm 7' -DOLLAMA_RUNNER_DIR="rocm_v7" \
        && cmake --build --parallel ${PARALLEL} --preset 'ROCm 7' \
        && cmake --install build --component HIP --strip --parallel ${PARALLEL}
RUN rm -f dist/lib/ollama/rocm/rocblas/library/*gfx90[06]*
RUN curl -fsSL https://golang.org/dl/go$(awk '/^go/ { print $2 }' go.mod).linux-$(case $(uname -m) in x86_64) echo amd64 ;; aarch64) echo arm64 ;; esac).tar.gz | tar xz -C /usr/local
ENV PATH=/usr/local/go/bin:$PATH
RUN go mod download
ARG GOFLAGS="'-ldflags=-w -s'"
ENV CGO_ENABLED=1
ARG CGO_CFLAGS
ARG CGO_CXXFLAGS
RUN --mount=type=cache,target=/root/.cache/go-build \
    go build -trimpath -buildmode=pie -o /bin/ollama .


COPY --from=builder /bin/ollama /bin/ollama
COPY --from=builder /tmp/ollama-src/dist/lib/ollama /lib/ollama

ENV LD_LIBRARY_PATH=/usr/lib/ollama:/usr/lib/ollama/rocm
ENV OLLAMA_HOST=0.0.0.0:11434
EXPOSE 11434
ENTRYPOINT ["/bin/ollama"]
CMD ["serve"]