FROM registry.fedoraproject.org/fedora:43 AS builder
# vim: filetype=dockerfile

ARG FLAVOR=rocm
ARG PARALLEL=8

ARG ROCM7VERSION=7.1
ARG CMAKEVERSION=3.31.2

# rocm 7.1 repo
RUN <<'EOF'
tee /etc/yum.repos.d/rocm.repo <<REPO
[ROCm-7.1]
name=ROCm7.1
baseurl=https://repo.radeon.com/rocm/el9/7.1/main
enabled=1
priority=50
gpgcheck=1
gpgkey=https://repo.radeon.com/rocm/rocm.gpg.key
REPO
EOF

# deps
RUN dnf -y --nodocs --setopt=install_weak_deps=False \
    --exclude='*sdk*' --exclude='*samples*' --exclude='*-doc*' --exclude='*-docs*' \
    install \
      make gcc cmake lld clang clang-devel compiler-rt libcurl-devel ninja-build \
      rocm-llvm rocm-device-libs hip-runtime-amd hip-devel \
      rocblas rocblas-devel hipblas hipblas-devel rocm-cmake libomp-devel libomp \
      rocminfo radeontop \
      clang ccache \
      git-core vim sudo rsync \
 && dnf clean all && rm -rf /var/cache/dnf/*

# rocm env
ENV ROCM_PATH=/opt/rocm \
    HIP_PATH=/opt/rocm \
    HIP_CLANG_PATH=/opt/rocm/llvm/bin \
    HIP_DEVICE_LIB_PATH=/opt/rocm/amdgcn/bitcode \
    PATH=/opt/rocm/bin:/opt/rocm/llvm/bin:$PATH


# profile
RUN printf '%s\n' \
  'export ROCBLAS_USE_HIPBLASLT=1' \
  > /etc/profile.d/rocm.sh && chmod +x /etc/profile.d/rocm.sh \
  && echo 'source /etc/profile.d/rocm.sh' >> /etc/bashrc

RUN git clone https://github.com/rjmalagon/ollama-linux-amd-apu.git /tmp/ollama-src
WORKDIR /tmp/ollama-src

ARG CMAKEVERSION
RUN curl -fsSL https://github.com/Kitware/CMake/releases/download/v${CMAKEVERSION}/cmake-${CMAKEVERSION}-linux-$(uname -m).tar.gz | tar xz -C /usr/local --strip-components 1
ENV LDFLAGS=-s


ENV PATH=/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/opt/rocm/bin:/opt/rocm/hcc/bin:$PATH
ARG PARALLEL
RUN --mount=type=cache,target=/root/.ccache \
    cmake --preset 'ROCm 7' -DOLLAMA_RUNNER_DIR="rocm_v7" \
        && cmake --build --parallel ${PARALLEL} --preset 'ROCm 7' \
        && cmake --install build --component HIP --strip --parallel ${PARALLEL}
RUN rm -f dist/lib/ollama/rocm/rocblas/library/*gfx90[06]*
RUN curl -fsSL https://golang.org/dl/go$(awk '/^go/ { print $2 }' go.mod).linux-$(case $(uname -m) in x86_64) echo amd64 ;; aarch64) echo arm64 ;; esac).tar.gz | tar xz -C /usr/local
ENV PATH=/usr/local/go/bin:$PATH
RUN go mod download
ARG GOFLAGS="'-ldflags=-w -s'"
ENV CGO_ENABLED=1
ARG CGO_CFLAGS
ARG CGO_CXXFLAGS
RUN --mount=type=cache,target=/root/.cache/go-build \
    go build -trimpath -buildmode=pie -o /bin/ollama .


COPY --from=builder /bin/ollama /bin/ollama
COPY --from=builder /tmp/ollama-src/dist/lib/ollama /lib/ollama

ENV LD_LIBRARY_PATH=/usr/lib/ollama:/usr/lib/ollama/rocm
ENV OLLAMA_HOST=0.0.0.0:11434
EXPOSE 11434
ENTRYPOINT ["/bin/ollama"]
CMD ["serve"]