# build stage
FROM registry.fedoraproject.org/fedora:43 AS builder


# rocm 7.1 repo
RUN <<'EOF'
tee /etc/yum.repos.d/rocm.repo <<REPO
[ROCm-7.1]
name=ROCm7.1
baseurl=https://repo.radeon.com/rocm/el9/7.1/main
enabled=1
priority=50
gpgcheck=1
gpgkey=https://repo.radeon.com/rocm/rocm.gpg.key
REPO
EOF



# Install base build tools and utilities
RUN dnf -y --nodocs --setopt=install_weak_deps=False \
    install \
      make gcc gcc-c++ cmake ninja-build \
      git-core vim sudo rsync curl wget bash ca-certificates \
 && dnf clean all && rm -rf /var/cache/dnf/*

# Install LLVM/Clang toolchain
RUN dnf -y --nodocs --setopt=install_weak_deps=False \
    install \
      lld clang clang-devel compiler-rt \
      rocm-llvm \
 && dnf clean all && rm -rf /var/cache/dnf/*

# Install ROCm runtime components
RUN dnf -y --nodocs --setopt=install_weak_deps=False \
    install \
      rocm-runtime rocm-device-libs hip-runtime-amd \
      hsa-rocr rocminfo rocm-smi radeontop \
 && dnf clean all && rm -rf /var/cache/dnf/*

# Install ROCm development libraries
RUN dnf -y --nodocs --setopt=install_weak_deps=False \
    install \
      hip-devel rocm-dev rocm-libs rocm-cmake \
      libomp-devel libomp \
 && dnf clean all && rm -rf /var/cache/dnf/*

# Install ROCm math libraries
RUN dnf -y --nodocs --setopt=install_weak_deps=False \
    install \
      rocblas rocblas-devel \
      hipblas hipblas-devel \
 && dnf clean all && rm -rf /var/cache/dnf/*

# Install additional development dependencies
RUN dnf -y --nodocs --setopt=install_weak_deps=False \
    install \
      libcurl-devel golang \
      vulkan-headers vulkan-loader vulkan-loader-devel glslc \
 && dnf clean all && rm -rf /var/cache/dnf/*

RUN dnf -y install glslang python-devel @development-tools


# shell
CMD ["/bin/bash"]
