# ComfyUI with ROCm support for different AMD GPU architectures
FROM rocm/dev-ubuntu-24.04:7.1-complete AS default

RUN apt-get update

#Known good packages for ComfyUI on ROCm
RUN apt-get install -y ca-certificates libvulkan1 git python3-venv python3-full python3-pip


# Install ROCm libraries required for PyTorch and ComfyUI
RUN apt-get install -y migraphx
 
#install dependencies for libgthread
RUN apt-get install -y \
       libglib2.0-0 libgthread-2.0-0 libgtk-3-0 libgdk-pixbuf2.0-0 \
       libgl1 libglib2.0-dev libsm6 libxext6 libxrender-dev \
       libgomp1 libgstreamer1.0-0 libgstreamer-plugins-base1.0-0 \
       libegl1 libxrandr2 libxss1 libxcursor1 libxcomposite1 libxdamage1 \
       libxfixes3 libxi6 libxinerama1 libxrandr2 libxrender1

RUN  apt-get clean

RUN rm -rf /var/lib/apt/lists/*


# Copy ComfyUI repository and pre-built virtual environment
WORKDIR /app

# Expose default ComfyUI port
EXPOSE 8188

COPY comfyui-build/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Set the default command to run ComfyUI with ROCm optimizations
ENTRYPOINT ["/docker-entrypoint.sh"]