FROM docker.io/getterup/fedora-rocm7.1:latest
# vim: filetype=dockerfile

# Copy built ollama binary and libraries from build output
COPY ./ollama-build/ollama-build-output/bin/ollama /usr/bin/ollama
COPY ./ollama-build/ollama-build-output/lib/ollama /usr/lib/ollama

# Set executable permissions
RUN chmod +x /usr/bin/ollama

# Expose port
ENV OLLAMA_HOST=0.0.0.0:11434
EXPOSE 11434

ENTRYPOINT ["/usr/bin/ollama", "serve"]